Create Table Usuarios(
	ID_USUARIO int AUTO_INCREMENT,
	NOMBRE varchar(255),
	CONTRASEÑA varchar(255),
	PRIMARY KEY(ID_USUARIO));

Create Table Tareas(
	ID_TAREA Int AUTO_INCREMENT,
	ID_USUARIO Int,
	TITULO Varchar(255),
    ESTADO Varchar(255),
    PRIMARY KEY(ID_TAREA),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO));
